from labyrinth_test_case import LabyrinthTestCase
from lwotai.labyrinth import Labyrinth


class WarOfIdeasHandlerTest(LabyrinthTestCase):
    """Test War of Ideas Handler"""

    def test_fail_rolls(self):
        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)
        app.handle_muslim_woi(1, "Gulf States")
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)
        app.handle_muslim_woi(2, "Gulf States")
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)
        app.handle_muslim_woi(3, "Gulf States")
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)
        app.handle_muslim_woi(4, "Gulf States")
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 1)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)
        app.handle_muslim_woi(5, "Gulf States")
        self.assertTrue(app.get_country("Gulf States").is_good())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Gulf States").is_fair())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)
        app.handle_muslim_woi(6, "Gulf States")
        self.assertTrue(app.get_country("Gulf States").is_good())
        self.assertTrue(app.get_country("Gulf States").is_ally())
        self.assertEqual(app.get_country("Gulf States").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)
        app.handle_muslim_woi(1, "Pakistan")
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)
        app.handle_muslim_woi(2, "Pakistan")
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)
        app.handle_muslim_woi(3, "Pakistan")
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)
        app.handle_muslim_woi(4, "Pakistan")
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 1)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)
        app.handle_muslim_woi(5, "Pakistan")
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_ally())
        self.assertEqual(app.get_country("Pakistan").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_neutral())
        self.assertEqual(app.get_country("Pakistan").aid, 0)
        app.handle_muslim_woi(6, "Pakistan")
        self.assertTrue(app.get_country("Pakistan").is_fair())
        self.assertTrue(app.get_country("Pakistan").is_ally())
        self.assertEqual(app.get_country("Pakistan").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)
        app.handle_muslim_woi(1, "Saudi Arabia")
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)
        app.handle_muslim_woi(2, "Saudi Arabia")
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)
        app.handle_muslim_woi(3, "Saudi Arabia")
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)
        app.handle_muslim_woi(4, "Saudi Arabia")
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 1)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)
        app.handle_muslim_woi(5, "Saudi Arabia")
        self.assertTrue(app.get_country("Saudi Arabia").is_fair())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.get_country("Saudi Arabia").is_poor())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)
        app.handle_muslim_woi(6, "Saudi Arabia")
        self.assertTrue(app.get_country("Saudi Arabia").is_fair())
        self.assertTrue(app.get_country("Saudi Arabia").is_ally())
        self.assertEqual(app.get_country("Saudi Arabia").aid, 0)